# Objects

Everything in Python is an object. The following code snippets are aimed at showing some of the features of objects and its properties and methods.

> Use the `TAB` key after writing few characters to trigger autocompletion of object properties and methods.`

## Methods

Methods are functions attached to an object. Below there are few examples:

- sort() method of list objects. This method sorts the elements of a list.

- upper() method of string objects. This method converts all the letters of a string to upper case letters.

- mean() method of Numpy objects. This method computes the arithmetic average of a Numpy array either column-wise or row-wise.


In [6]:
# sort() method of a list object

a = [2,1,3]    # Generate a trivial list
print(type(a)) # Print its type
print(a.sort)  # Show that sort() is a method of lists. Print not using the ()

# The address 0x10b662380 is a pointer in memory.
 
a.sort()  # Invoke the built-in method
print(a) # Print the sorted list


<class 'list'>
<built-in method sort of list object at 0x10b662380>
[1, 2, 3]


In [8]:
# upper() method of string objects

b = "soil"     # Generate a string
print(type(b)) # Print its type
print(b.upper) # # Show that upper() is a method of lists. Invoke not using the ()
print(b.upper()) # Let's use the built-in method and print the upper case word


<class 'str'>
<built-in method upper of str object at 0x108c31170>
SOIL


In [11]:
# Import numpy module
import numpy as np

np.random.seed(1) # Set seed for reproducibility
array = np.array(np.random.randint(12, size=(3,4))) # Create array of 3 rows and 4 columns
print(array)
print(type(array)) # Print object type
print(array.mean) # Showthat .mean() is a method of numpy objects
print(array.mean(axis=0)) # Invoke mean() along axis 0 (column-wise)
print(array.mean(axis=1)) # Invoke mean() along axis 1 (row-wise)


[[ 5 11  8  9]
 [11  5  0  0]
 [ 1  7  6  9]]
<class 'numpy.ndarray'>
<built-in method mean of numpy.ndarray object at 0x10bbf83f0>
[5.66666667 7.66666667 4.66666667 6.        ]
[8.25 4.   5.75]


## Properties

In [64]:
# These are properties of the object

# Type of elements in the array (float 64 bits in this case)
print(type(array.dtype))
print(array.dtype)
      
# Dimensions of the array
print(type(array.shape))
print(array.shape) # returns a tuple

# Total number of elements
print(type(array.size))
print(array.size)


<class 'numpy.dtype'>
float64
<class 'tuple'>
(3, 4)
<class 'int'>
12


## References

Python official documentation about objects and classes: https://docs.python.org/3/tutorial/classes.html